### PR TITLE
add strict validation for input

### PR DESCRIPTION
**Pull request by ydayagi**
FLPATH-1618
https://issues.redhat.com/browse/FLPATH-1618

### CODE REVIEW

**Comment by ydayagi** [comment]
@gabriel-farache @gciavarrini @pkliczewski @masayag

**Comment by ydayagi** [comment]
@batzionb @mareklibra

**Review by batzionb — APPROVED** [review]

**Review by pkliczewski — COMMENTED** [review]
/lgtm

**Review by gabriel-farache — APPROVED** [review]

**Pull request merged**
