### PR TITLE
Add M2K doc

### PR DESCRIPTION
**Pull request by gabriel-farache**
Add M2K doc for website to use

### CODE REVIEW

**Comment by masayag** [comment]
@rgolangh can you provide tips for this PR so the document will be rendered into the website?

**Comment by gabriel-farache** [comment]
> @rgolangh can you provide tips for this PR so the document will be rendered in the website?


From what I understand from the website project, I'll need to run
```
./generate-doc-for-repo.sh \
    https://github.com/parodos-dev/serverless-workflows/blob/main/move2kube/README.md > content/docs/workflows/m2k.md
```
```

**Comment by masayag** [comment]
> > @rgolangh can you provide tips for this PR so the document will be rendered in the website?
> 
> @masayag From what I understand from the website project, I'll need to run
> 
> ```
> ./generate-doc-for-repo.sh \
>     https://github.com/parodos-dev/serverless-workflows/blob/main/move2kube/README.md > content/docs/workflows/m2k.md
> ```
 
I think this is only part of it. Since there are images included, it might be needed to reference them by their full path so they will be rendered on the website. Haven't tested it myself, but if you'd like to give it a try and see how that goes.

**Comment by gabriel-farache** [comment]
>>>@rgolangh can you provide tips for this PR so the document will be rendered in the website?

>>@masayag From what I understand from the website project, I'll need to run
./generate-doc-for-repo.sh \
    https://github.com/parodos-dev/serverless-workflows/blob/main/move2kube/README.md > content/docs/workflows/m2k.md

>I think this is only part of it. Since there are images included, it might be needed to reference them by their full path so they will be rendered on the website. Haven't tested it myself, but if you'd like to give it a try and see how that goes.
I ran it and indeed, the image are broken, even by putting absolute link to the repo the images are broken, @rgolangh do you know how we could include images?

**Comment by gabriel-farache** [comment]
@masayag @rgolangh With the latest commit, it works, the images are rendered: we have to put gh raw URLs for the images to be rendered by Hugo

**Review by masayag — APPROVED** [review]

**Pull request merged**
