### PR TITLE
e2e: move to use the maintained orchestrator-k8s helm chart

### PR DESCRIPTION
**Pull request by rgolangh**
Signed-off-by: Roy Golan <rgolan@redhat.com>

### CODE REVIEW

**Comment by rgolangh** [comment]
@gfarache @masayag hoping this change will help catching errors like the auth issues with notifs more quicker

This will work nicely with the change by @masayag to always send notifications.

Also, I assume the orchestrator-k8s chart would need some changes, like bumping the notification plugin versions, and few config changes.

**Comment by masayag** [comment]
> @gfarache @masayag hoping this change will help catching errors like the auth issues with notifs more quicker
> 
> This will work nicely with the change by @masayag to always send notifications.
> 
> Also, I assume the orchestrator-k8s chart would need some changes, like bumping the notification plugin versions, and few config changes.

The required changes are replacing the existing notifications plugins with the new one and add also the signal plugin.
ATM we have those artifacts on in the staging registry - https://npm.stage.registry.redhat.com/

**Comment by rgolangh** [comment]
> > @gfarache @masayag hoping this change will help catching errors like the auth issues with notifs more quicker
> > This will work nicely with the change by @masayag to always send notifications.
> > Also, I assume the orchestrator-k8s chart would need some changes, like bumping the notification plugin versions, and few config changes.
> 
> The required changes are replacing the existing notifications plugins with the new one and add also the signal plugin. ATM we have those artifacts on in the staging registry - https://npm.stage.registry.redhat.com/

no upstream packages?

**Comment by masayag** [comment]
> > > @gfarache @masayag hoping this change will help catching errors like the auth issues with notifs more quicker
> > > This will work nicely with the change by @masayag to always send notifications.
> > > Also, I assume the orchestrator-k8s chart would need some changes, like bumping the notification plugin versions, and few config changes.
> > 
> > 
> > The required changes are replacing the existing notifications plugins with the new one and add also the signal plugin. ATM we have those artifacts on in the staging registry - https://npm.stage.registry.redhat.com/
> 
> no upstream packages?

I don't this there is a version of those plugins released as dynamic plugins to the upstream.
Let's confirm this with @batzionb @mareklibra

**Comment by batzionb** [comment]
There are upstream plugins for the orchestrator plugin
Different story with notifications plugins

**Comment by rgolangh** [comment]
closing in favour of #313

**Pull request closed without merging**
