### PR TITLE
Add staging branch

### PR DESCRIPTION
**Pull request by masayag**
Signed-off-by: Moti Asayag <masayag@redhat.com>

rh-pre-commit.version: 2.3.0
rh-pre-commit.check-secrets: ENABLED

### CODE REVIEW

**Comment by masayag** [comment]
probably it would be better to push images with a prefix `staging-` for the image tag
any opinions on a better option?

**Comment by gabriel-farache** [comment]
> probably it would be better to push images with a prefix staging- for the image tag

I would do suffix instead of prefix but that a technicality

So now the process would be to first push to stagging for in progress work and then to main? Or that all PR will be merged to stagging and when we want to release we push to main?

**Comment by rgolangh** [comment]
> probably it would be better to push images with a prefix `staging-` for the image tag any opinions on a better option?
 
Can you add the reason for having a stagihng branch?
To the point of nameing, I think the staging should be expressed in the repository name, not the image name or tag.

**Comment by masayag** [comment]
> I would do suffix instead of prefix but that a technicality

my bad - meant for a suffix.

**Comment by masayag** [comment]
> Can you add the reason for having a stagihng branch?

The idea for this branch is to enable an early testing of the pre-GA components (RHDH and Sonataflow), without affecting the upstream chart. This chart is designed for internal testing to identify any potential issues with the next versions of RHDH and Soantaflow. This chart pulls the pre-GA components differently than the GA, therefore not a good candidate to be merged to the upstream branch.

> To the point of naming, I think the staging should be expressed in the repository name, not the image name or tag.

I was thinking of `mta-0.02-rc1` or `mta-0.02-staging` or something that will not be visible when listing the charts without the `--version` flag or not being installed automatically if the version is omitted.

**Pull request merged**
