### PR TITLE
add adoc for notifications openapi spec

### PR DESCRIPTION
**Pull request by ydayagi**

### CODE REVIEW

**Comment by gciavarrini** [comment]
Are the docs regenerated in case of a change in the specs? Or, how can the developer update the docs?

**Comment by ydayagi** [comment]
> Are the docs regenerated in case of a change in the specs? Or, how can the developer update the docs?

the spec was not auto-generated. therefore, its doc is not auto-generated.

**Comment by gciavarrini** [comment]
> > Are the docs regenerated in case of a change in the specs? Or, how can the developer update the docs?
> 
> the spec was not auto-generated. therefore, its doc is not auto-generated.

I see they aren't *auto* generated, but they are *generated* by OpenAPI tool (see [this section](https://github.com/parodos-dev/serverless-workflows/blob/f33cd4004e062af33bef6ebb2739d30d69be918e/shared/specs/notifications-openapi.adoc?plain=1#L2-L13) as reference). This reinforces my question about how developers can update the docs.

**Comment by ydayagi** [comment]
> > > Are the docs regenerated in case of a change in the specs? Or, how can the developer update the docs?
> > 
> > 
> > the spec was not auto-generated. therefore, its doc is not auto-generated.
> 
> I see they aren't _auto_ generated, but they are _generated_ by OpenAPI tool (see [this section](https://github.com/parodos-dev/serverless-workflows/blob/f33cd4004e062af33bef6ebb2739d30d69be918e/shared/specs/notifications-openapi.adoc?plain=1#L2-L13) as reference). This reinforces my question about how developers can update the docs.

a developer updates the spec, not the doc. the doc is either a result or a second step. if the developer knows how to create a spec then I am certain he/she knows how to generate a doc.

**Comment by gciavarrini** [comment]
I understand that you prioritize merging this PR, but neglecting clear contribution guidelines creates unnecessary back-and-forth discussions that waste everyone's time. Having a documented process for updating the docs is essential. I'll approve this PR for now, but moving forward, a documented process is expected to avoid similar situations.

**Review by gciavarrini — APPROVED** [review]

**Pull request merged**
