### PR TITLE
Move workflows into workflows sub-directory

### PR DESCRIPTION
**Pull request by gabriel-farache**
Closes https://issues.redhat.com/browse/FLPATH-1692

Move workflows into workflows sub-directory

### CODE REVIEW

**Comment by gabriel-farache** [comment]
For the konflux to be fixed, the PR will have to be merged then https://gitlab.cee.redhat.com/releng/konflux-release-data/-/blob/main/config/stone-prd-rh01.pg1f.p1/product/EnterpriseContractPolicy/registry-orchestrator-releng-serverless-workflows.yaml#L28 will have to be updated with new `main` sha

**Comment by gabriel-farache** [comment]
The E2E CI will fail until https://github.com/parodos-dev/orchestrator-helm-chart/pull/274 is merged

**Comment by ElaiShalevRH** [comment]
The changes look good
There are more locations that need changes now, like [serverless-workflows-config](https://github.com/search?q=repo%3Aparodos-dev%2Fserverless-workflows-config+serverless-workflows%2F&type=code) repo. 
Maybe also in the operator repo

**Comment by masayag** [comment]
> The changes look good There are more locations that need changes now, like [serverless-workflows-config](https://github.com/search?q=repo%3Aparodos-dev%2Fserverless-workflows-config+serverless-workflows%2F&type=code) repo. Maybe also in the operator repo

perhaps also in the github.com:parodos-dev/parodos-dev.github.io.git changes are required.

**Comment by gabriel-farache** [comment]
@ElaiShalevRH @masayag 
https://github.com/parodos-dev/serverless-workflows-config/pull/957 for the charts
https://github.com/parodos-dev/parodos-dev.github.io/pull/117 for the website

**Review by masayag — APPROVED** [review]

**Pull request merged**
