### PR TITLE
Fix lost event by manually sending the events

### PR DESCRIPTION
**Pull request by gabriel-farache**
Closes https://issues.redhat.com/browse/FLPATH-1206

If the M2K pod is deleted while waiting for the transformation callback, when the callback event is received, the workflow does not receive it, even if the pod was ready for a few minute before the event was sent.

The event is sent by the transformation knative function using FunQ. 

To fix the issue, instead of relying on FunQ to send the callback event, we are sending it explicitly/manually.

### CODE REVIEW

**Comment by pkliczewski** [comment]
@gabriel-farache thanks for this workaround, please open an issue for sonataFlow so it can be fixed properly.

**Comment by gabriel-farache** [comment]
@pkliczewski as discussed, this is not related to sonataflow, instead, as advised, I opened the bug for quarkus: https://github.com/quarkusio/quarkus/issues/40631

**Comment by gabriel-farache** [comment]
It seems that by using kafka broker instead of in-memory brojer, the issue is gone

I need to check again but the better solution would be to switch to using kafka broker

**Comment by masayag** [comment]
So with kafka enabled, can this PR be closed?

**Comment by gabriel-farache** [comment]
Yes

**Comment by rgolangh** [comment]
closing, based on last comments

**Pull request closed without merging**
