### PR TITLE
Use OSL 1.32 builder image

### PR DESCRIPTION
**Pull request by masayag**

### CODE REVIEW

**Comment by gabriel-farache** [comment]
Should we add also a dev dockerfile?

**Comment by masayag** [comment]
> Should we add also a dev dockerfile?

Do you mean to preserve the previous version of that file?

**Comment by gabriel-farache** [comment]
> Do you mean to preserve the previous version of that file? In other words, would should be the responsibility of the dev dockerfile?
Yes, so if we want to test something on a not yet released version of the builder, we can do it without touching the release file

**Comment by masayag** [comment]
> > Do you mean to preserve the previous version of that file? In other words, would should be the responsibility of the dev dockerfile?
> 
> Yes, so if we want to test something on a not yet released version of the builder, we can do it without touching the release file

That makes sense. I'll preserve the dev one.

**Pull request closed without merging**
