### PR TITLE
Use notifications specs from github repo

### PR DESCRIPTION
**Pull request by gabriel-farache**
Use notifications specs from github repo to avoid duplicate files in each workflow specs

### CODE REVIEW

**Comment by gabriel-farache** [comment]
@rgolangh in the MTA props, I do not see where you set the URL for the notification, is it missing?

**Comment by gabriel-farache** [comment]
/hold Do not merge until notification plugin is made a dynamic plugin: the PR uses the specs from release 1.0.3 (https://github.com/janus-idp/backstage-plugins/releases/tag/%40janus-idp%2Fplugin-notifications-backend%401.0.3) 
Also maybe waits for https://issues.redhat.com/browse/FLPATH-878 as it fixes bugs with arrays and the specs contains arrays (for actions and targetUsers for instance)

**Review by dmartinol — APPROVED** [review]
Thank you!

**Comment by masayag** [comment]
@gabriel-farache pls rebase.

**Review by dmartinol — APPROVED** [review]

**Comment by rgolangh** [comment]
> @rgolangh in the MTA props, I do not see where you set the URL for the notification, is it missing?

I think there's was a url in the openapi spec

**Comment by rgolangh** [comment]
So I still think we need a property for MTA for notification endpoint , because the default in the openapi spec 
is localhost:7007
@gabriel-farache  Can you please add `quarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL:http://orchestrator-backstage.orchestrator/api/notifications/}` to the application props of mta?

**Comment by rgolangh** [comment]
we would need to add , for e2e , an env variable to point at the e2e endpoint, similar to 
https://github.com/parodos-dev/serverless-workflows/blob/37054d2ff27d83fffa600475e77eca7f11c41e27/.github/workflows/mta-e2e.yaml#L103

**Comment by gabriel-farache** [comment]
> we would need to add , for e2e , an env variable to point at the e2e endpoint, similar to

@rgolangh or a kubectl patch to the props
```
kubectl patch configmap/m2k-props \
            --type merge \
            -p '{"data":{"move2kube_url": "http://move2kube-svc.default.svc.cluster.local:8080", "quarkus.rest-client.move2kube_yaml.url": "http://move2kube-svc.default.svc.cluster.local:8080", "broker_url": "http://broker-ingress.knative-eventing.svc.cluster.local/default/default", "quarkus.rest-client.notifications_yaml.url": "http://janus-idp-workflows-backstage.default.svc.cluster.local:7007/api/notifications/"}}'
```
But then a pod restart is required

**Review by dmartinol — APPROVED** [review]

**Comment by gabriel-farache** [comment]
> So I still think we need a property for MTA for notification endpoint , because the default in the openapi spec
is localhost:7007
@gabriel-farache Can you please add quarkus.rest-client.notifications.url=${BACKSTAGE_NOTIFICATIONS_URL:http://orchestrator-backstage.orchestrator/api/notifications/} to the application props of mta?

> we would need to add , for e2e , an env variable to point at the e2e endpoint, similar to

@rgolangh  done :)

**Comment by gabriel-farache** [comment]
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3377 is merged so sonataflow should have the openapi generator version that includes the fix in tomorrow's nightly

**Review by masayag — APPROVED** [review]

**Comment by gabriel-farache** [comment]
> @gabriel-farache some of the changes were pushed in a previously merged PR. Please rebase.


@masayag done

**Pull request merged**
