### PR TITLE
adding hack directory + openAPI reducing script

### PR DESCRIPTION
**Pull request by ElaiShalevRH**
I've added a directory to store 'hacks' scripts, and tools to help with ongoing serverless-workflow tasks. 
I've included a script originally found [here](https://github.com/parodos-dev/serverless-workflows/blob/feat/aap-db-deploy/extract_from_swagger_spec.py) and implemented some changes in it to allow YAML inputs.

### CODE REVIEW

**Comment by ElaiShalevRH** [comment]
@masayag @gabriel-farache

**Comment by ElaiShalevRH** [comment]
Maybe we need to decide on a standardized term (reducing / reduce / filtering etc)

**Comment by masayag** [comment]
> Maybe we need to decide on a standardized term (reducing / reduce / filtering etc)

IMO the term `extract` or `filter` represent the action done by the script better than `reduce`.

**Comment by masayag** [comment]
@ElaiShalevRH in the future, it would be nice to add a unit test for this one (a low priority item to work on)

**Pull request merged**
